// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.privacy-request-worker@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PRIVACY_REQUEST_WORKER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PRIVACY_REQUEST_WORKER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_privacy_request_worker { () => { "{\"capability_id\":\"lenso.privacy-request-worker@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"claim_next\",\"claim_request\",\"complete_request\",\"fail_request\",\"process_request\",\"retry_request\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_privacy_request_worker_client { () => { "{\"capability_id\":\"lenso.privacy-request-worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_privacy_request_worker_client { () => { "{\"capability_id\":\"lenso.privacy-request-worker@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CLAIM_NEXT_OPERATION: &str = "claim_next";
pub const CLAIM_REQUEST_OPERATION: &str = "claim_request";
pub const COMPLETE_REQUEST_OPERATION: &str = "complete_request";
pub const FAIL_REQUEST_OPERATION: &str = "fail_request";
pub const PROCESS_REQUEST_OPERATION: &str = "process_request";
pub const RETRY_REQUEST_OPERATION: &str = "retry_request";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimNextRequest {
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "kind")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kind: Option<ClaimNextRequestKind>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimNextRequestKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimNextResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: ClaimNextResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ClaimNextResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ClaimNextResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimNextResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimNextResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimNextResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ClaimNextError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OperationInProgress,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimRequestRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: ClaimRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ClaimRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ClaimRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ClaimRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ClaimRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OperationInProgress,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequestRequest {
    #[serde(rename = "completion_reference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completion_reference: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: CompleteRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: CompleteRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: CompleteRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CompleteRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CompleteRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CompleteRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OperationInProgress,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FailRequestRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "retryable")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retryable: bool,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FailRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: FailRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: FailRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: FailRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum FailRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum FailRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum FailRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum FailRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OperationInProgress,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessRequestRequest {
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "manual_evidence_reference")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manual_evidence_reference: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessRequestResponse {
    #[serde(rename = "all_steps_completed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub all_steps_completed: bool,
    #[serde(rename = "completed_steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_steps: i64,
    #[serde(rename = "failed_steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failed_steps: i64,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "pending_steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub pending_steps: i64,
    #[serde(rename = "request")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request: ProcessRequestResponseRequest,
    #[serde(rename = "steps")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub steps: Vec<ProcessRequestResponseStepsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessRequestResponseRequest {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: ProcessRequestResponseRequestIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ProcessRequestResponseRequestKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ProcessRequestResponseRequestState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessRequestResponseRequestIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessRequestResponseRequestKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessRequestResponseRequestState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessRequestResponseStepsItem {
    #[serde(rename = "attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempts: i64,
    #[serde(rename = "error_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub error_code: Option<String>,
    #[serde(rename = "provider_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider_instance: String,
    #[serde(rename = "provider_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider_kind: ProcessRequestResponseStepsItemProviderKind,
    #[serde(rename = "sequence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sequence: i64,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ProcessRequestResponseStepsItemStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessRequestResponseStepsItemProviderKind {
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "retention")]
    Retention,
    #[serde(rename = "manual")]
    Manual,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ProcessRequestResponseStepsItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProcessRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OperationInProgress,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryRequestRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RetryRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: RetryRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: RetryRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: RetryRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RetryRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RetryRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    OperationInProgress,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerClaimNext;
impl RequestCapability for PrivacyRequestWorkerClaimNext {
    type Request = ClaimNextRequest;
    type Response = ClaimNextResponse;
    type DomainError = ClaimNextError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CLAIM_NEXT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).claim_next(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerClaimRequest;
impl RequestCapability for PrivacyRequestWorkerClaimRequest {
    type Request = ClaimRequestRequest;
    type Response = ClaimRequestResponse;
    type DomainError = ClaimRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CLAIM_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).claim_request(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerCompleteRequest;
impl RequestCapability for PrivacyRequestWorkerCompleteRequest {
    type Request = CompleteRequestRequest;
    type Response = CompleteRequestResponse;
    type DomainError = CompleteRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != COMPLETE_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).complete_request(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerFailRequest;
impl RequestCapability for PrivacyRequestWorkerFailRequest {
    type Request = FailRequestRequest;
    type Response = FailRequestResponse;
    type DomainError = FailRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != FAIL_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).fail_request(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerProcessRequest;
impl RequestCapability for PrivacyRequestWorkerProcessRequest {
    type Request = ProcessRequestRequest;
    type Response = ProcessRequestResponse;
    type DomainError = ProcessRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PROCESS_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).process_request(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerRetryRequest;
impl RequestCapability for PrivacyRequestWorkerRetryRequest {
    type Request = RetryRequestRequest;
    type Response = RetryRequestResponse;
    type DomainError = RetryRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RETRY_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestWorkerRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).retry_request(context, request)
    }
}

impl serde::Serialize for ClaimNextError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ClaimNextError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ClaimRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ClaimRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CompleteRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for FailRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for FailRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ProcessRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ProcessRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RetryRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::OperationInProgress => serializer.serialize_str("operation_in_progress"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RetryRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "operation_in_progress" => Ok(Self::OperationInProgress),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_claim_next_request(value: &ClaimNextRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_next_request(wire: &str) -> Result<ClaimNextRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_next_response(value: &ClaimNextResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_next_response(wire: &str) -> Result<ClaimNextResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_next_error(value: &ClaimNextError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_next_error(wire: &str) -> Result<ClaimNextError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_claim_request_request(value: &ClaimRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_request_request(wire: &str) -> Result<ClaimRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_request_response(value: &ClaimRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_request_response(wire: &str) -> Result<ClaimRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_request_error(value: &ClaimRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_request_error(wire: &str) -> Result<ClaimRequestError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_complete_request_request(value: &CompleteRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request_request(wire: &str) -> Result<CompleteRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_request_response(value: &CompleteRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request_response(wire: &str) -> Result<CompleteRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_request_error(value: &CompleteRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request_error(wire: &str) -> Result<CompleteRequestError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_fail_request_request(value: &FailRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_request_request(wire: &str) -> Result<FailRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_fail_request_response(value: &FailRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_request_response(wire: &str) -> Result<FailRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_fail_request_error(value: &FailRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_request_error(wire: &str) -> Result<FailRequestError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_process_request_request(value: &ProcessRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_request_request(wire: &str) -> Result<ProcessRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_request_response(value: &ProcessRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_request_response(wire: &str) -> Result<ProcessRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_request_error(value: &ProcessRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_request_error(wire: &str) -> Result<ProcessRequestError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_retry_request_request(value: &RetryRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_request_request(wire: &str) -> Result<RetryRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_request_response(value: &RetryRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_request_response(wire: &str) -> Result<RetryRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_retry_request_error(value: &RetryRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_retry_request_error(wire: &str) -> Result<RetryRequestError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWorkerClaimNextResult {
    fn __lenso_into_result(self) -> Result<Result<ClaimNextResponse, ClaimNextError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWorkerClaimNextResult for Result<ClaimNextResponse, ClaimNextError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimNextResponse, ClaimNextError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWorkerClaimNextResult for Result<Result<ClaimNextResponse, ClaimNextError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ClaimNextResponse, ClaimNextError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWorkerClaimNextResult for Result<ClaimNextResponse, lenso_plugin_authoring::PluginError<ClaimNextError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ClaimNextResponse, ClaimNextError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWorkerClaimNextResult for Result<ClaimNextResponse, PrivacyRequestWorkerClaimNextInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimNextResponse, ClaimNextError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWorkerClaimNextInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWorkerClaimNextInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWorkerClaimRequestResult {
    fn __lenso_into_result(self) -> Result<Result<ClaimRequestResponse, ClaimRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWorkerClaimRequestResult for Result<ClaimRequestResponse, ClaimRequestError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimRequestResponse, ClaimRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWorkerClaimRequestResult for Result<Result<ClaimRequestResponse, ClaimRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ClaimRequestResponse, ClaimRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWorkerClaimRequestResult for Result<ClaimRequestResponse, lenso_plugin_authoring::PluginError<ClaimRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ClaimRequestResponse, ClaimRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWorkerClaimRequestResult for Result<ClaimRequestResponse, PrivacyRequestWorkerClaimRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimRequestResponse, ClaimRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWorkerClaimRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWorkerClaimRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWorkerCompleteRequestResult {
    fn __lenso_into_result(self) -> Result<Result<CompleteRequestResponse, CompleteRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWorkerCompleteRequestResult for Result<CompleteRequestResponse, CompleteRequestError> {
    fn __lenso_into_result(self) -> Result<Result<CompleteRequestResponse, CompleteRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWorkerCompleteRequestResult for Result<Result<CompleteRequestResponse, CompleteRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CompleteRequestResponse, CompleteRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWorkerCompleteRequestResult for Result<CompleteRequestResponse, lenso_plugin_authoring::PluginError<CompleteRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CompleteRequestResponse, CompleteRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWorkerCompleteRequestResult for Result<CompleteRequestResponse, PrivacyRequestWorkerCompleteRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CompleteRequestResponse, CompleteRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWorkerCompleteRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWorkerCompleteRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWorkerFailRequestResult {
    fn __lenso_into_result(self) -> Result<Result<FailRequestResponse, FailRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWorkerFailRequestResult for Result<FailRequestResponse, FailRequestError> {
    fn __lenso_into_result(self) -> Result<Result<FailRequestResponse, FailRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWorkerFailRequestResult for Result<Result<FailRequestResponse, FailRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<FailRequestResponse, FailRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWorkerFailRequestResult for Result<FailRequestResponse, lenso_plugin_authoring::PluginError<FailRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<FailRequestResponse, FailRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWorkerFailRequestResult for Result<FailRequestResponse, PrivacyRequestWorkerFailRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<FailRequestResponse, FailRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWorkerFailRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWorkerFailRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWorkerProcessRequestResult {
    fn __lenso_into_result(self) -> Result<Result<ProcessRequestResponse, ProcessRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWorkerProcessRequestResult for Result<ProcessRequestResponse, ProcessRequestError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessRequestResponse, ProcessRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWorkerProcessRequestResult for Result<Result<ProcessRequestResponse, ProcessRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ProcessRequestResponse, ProcessRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWorkerProcessRequestResult for Result<ProcessRequestResponse, lenso_plugin_authoring::PluginError<ProcessRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ProcessRequestResponse, ProcessRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWorkerProcessRequestResult for Result<ProcessRequestResponse, PrivacyRequestWorkerProcessRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessRequestResponse, ProcessRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWorkerProcessRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWorkerProcessRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWorkerRetryRequestResult {
    fn __lenso_into_result(self) -> Result<Result<RetryRequestResponse, RetryRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWorkerRetryRequestResult for Result<RetryRequestResponse, RetryRequestError> {
    fn __lenso_into_result(self) -> Result<Result<RetryRequestResponse, RetryRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWorkerRetryRequestResult for Result<Result<RetryRequestResponse, RetryRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RetryRequestResponse, RetryRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWorkerRetryRequestResult for Result<RetryRequestResponse, lenso_plugin_authoring::PluginError<RetryRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RetryRequestResponse, RetryRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWorkerRetryRequestResult for Result<RetryRequestResponse, PrivacyRequestWorkerRetryRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RetryRequestResponse, RetryRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWorkerRetryRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWorkerRetryRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait PrivacyRequestWorkerProvider: fmt::Debug + 'static {
    fn claim_next(&self, context: InvocationContext, request: ClaimNextRequest) -> NativeRequestFuture<PrivacyRequestWorkerClaimNext>;
    fn claim_request(&self, context: InvocationContext, request: ClaimRequestRequest) -> NativeRequestFuture<PrivacyRequestWorkerClaimRequest>;
    fn complete_request(&self, context: InvocationContext, request: CompleteRequestRequest) -> NativeRequestFuture<PrivacyRequestWorkerCompleteRequest>;
    fn fail_request(&self, context: InvocationContext, request: FailRequestRequest) -> NativeRequestFuture<PrivacyRequestWorkerFailRequest>;
    fn process_request(&self, context: InvocationContext, request: ProcessRequestRequest) -> NativeRequestFuture<PrivacyRequestWorkerProcessRequest>;
    fn retry_request(&self, context: InvocationContext, request: RetryRequestRequest) -> NativeRequestFuture<PrivacyRequestWorkerRetryRequest>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_privacy_request_worker {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPrivacyRequestWorker;
        impl $crate::PrivacyRequestWorkerProvider for $plugin {
        fn claim_next(&self, context: __LensoNativeSupportPrivacyRequestWorker::InvocationContext, request: $crate::ClaimNextRequest) -> __LensoNativeSupportPrivacyRequestWorker::NativeRequestFuture<$crate::PrivacyRequestWorkerClaimNext> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::claim_next(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWorkerClaimNextResult::__lenso_into_result(result)
            })
        }
        fn claim_request(&self, context: __LensoNativeSupportPrivacyRequestWorker::InvocationContext, request: $crate::ClaimRequestRequest) -> __LensoNativeSupportPrivacyRequestWorker::NativeRequestFuture<$crate::PrivacyRequestWorkerClaimRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::claim_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWorkerClaimRequestResult::__lenso_into_result(result)
            })
        }
        fn complete_request(&self, context: __LensoNativeSupportPrivacyRequestWorker::InvocationContext, request: $crate::CompleteRequestRequest) -> __LensoNativeSupportPrivacyRequestWorker::NativeRequestFuture<$crate::PrivacyRequestWorkerCompleteRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::complete_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWorkerCompleteRequestResult::__lenso_into_result(result)
            })
        }
        fn fail_request(&self, context: __LensoNativeSupportPrivacyRequestWorker::InvocationContext, request: $crate::FailRequestRequest) -> __LensoNativeSupportPrivacyRequestWorker::NativeRequestFuture<$crate::PrivacyRequestWorkerFailRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::fail_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWorkerFailRequestResult::__lenso_into_result(result)
            })
        }
        fn process_request(&self, context: __LensoNativeSupportPrivacyRequestWorker::InvocationContext, request: $crate::ProcessRequestRequest) -> __LensoNativeSupportPrivacyRequestWorker::NativeRequestFuture<$crate::PrivacyRequestWorkerProcessRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::process_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWorkerProcessRequestResult::__lenso_into_result(result)
            })
        }
        fn retry_request(&self, context: __LensoNativeSupportPrivacyRequestWorker::InvocationContext, request: $crate::RetryRequestRequest) -> __LensoNativeSupportPrivacyRequestWorker::NativeRequestFuture<$crate::PrivacyRequestWorkerRetryRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::retry_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWorkerRetryRequestResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct PrivacyRequestWorkerRequestEndpoint { provider: Rc<dyn PrivacyRequestWorkerProvider> }

#[derive(Debug)]
pub struct PrivacyRequestWorkerEndpoint<P: PrivacyRequestWorkerProvider> { provider: Rc<P>, request_endpoint: PrivacyRequestWorkerRequestEndpoint }
impl<P: PrivacyRequestWorkerProvider> PrivacyRequestWorkerEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PrivacyRequestWorkerProvider> = provider.clone();
        Self { provider, request_endpoint: PrivacyRequestWorkerRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PrivacyRequestWorkerProvider> NativeRequestEndpoint for PrivacyRequestWorkerEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CLAIM_NEXT_OPERATION,
        CLAIM_REQUEST_OPERATION,
        COMPLETE_REQUEST_OPERATION,
        FAIL_REQUEST_OPERATION,
        PROCESS_REQUEST_OPERATION,
        RETRY_REQUEST_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CLAIM_NEXT_OPERATION => {
                let Ok(request) = request.downcast::<ClaimNextRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).claim_next(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            CLAIM_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<ClaimRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).claim_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            COMPLETE_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<CompleteRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).complete_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            FAIL_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<FailRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).fail_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PROCESS_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<ProcessRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).process_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RETRY_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<RetryRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).retry_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_privacy_request_worker {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::PrivacyRequestWorkerEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_privacy_request_worker {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_privacy_request_worker!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct PrivacyRequestWorkerClient {
    claim_next: NativeRequestHandle<PrivacyRequestWorkerClaimNext>,
    claim_request: NativeRequestHandle<PrivacyRequestWorkerClaimRequest>,
    complete_request: NativeRequestHandle<PrivacyRequestWorkerCompleteRequest>,
    fail_request: NativeRequestHandle<PrivacyRequestWorkerFailRequest>,
    process_request: NativeRequestHandle<PrivacyRequestWorkerProcessRequest>,
    retry_request: NativeRequestHandle<PrivacyRequestWorkerRetryRequest>,
}
impl PrivacyRequestWorkerClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn claim_next(&self, request: ClaimNextRequest) -> Result<ClaimNextResponse, PrivacyRequestWorkerClaimNextInvocationError> {
        self.claim_next.invoke(CLAIM_NEXT_OPERATION, request).await
            .map_err(PrivacyRequestWorkerClaimNextInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerClaimNextInvocationError::Domain)
    }

    pub async fn claim_next_with_context(&self, context: InvocationContext, request: ClaimNextRequest) -> Result<ClaimNextResponse, PrivacyRequestWorkerClaimNextInvocationError> {
        self.claim_next.invoke_with_context(CLAIM_NEXT_OPERATION, context, request).await
            .map_err(PrivacyRequestWorkerClaimNextInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerClaimNextInvocationError::Domain)
    }

    pub async fn claim_request(&self, request: ClaimRequestRequest) -> Result<ClaimRequestResponse, PrivacyRequestWorkerClaimRequestInvocationError> {
        self.claim_request.invoke(CLAIM_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestWorkerClaimRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerClaimRequestInvocationError::Domain)
    }

    pub async fn claim_request_with_context(&self, context: InvocationContext, request: ClaimRequestRequest) -> Result<ClaimRequestResponse, PrivacyRequestWorkerClaimRequestInvocationError> {
        self.claim_request.invoke_with_context(CLAIM_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestWorkerClaimRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerClaimRequestInvocationError::Domain)
    }

    pub async fn complete_request(&self, request: CompleteRequestRequest) -> Result<CompleteRequestResponse, PrivacyRequestWorkerCompleteRequestInvocationError> {
        self.complete_request.invoke(COMPLETE_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestWorkerCompleteRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerCompleteRequestInvocationError::Domain)
    }

    pub async fn complete_request_with_context(&self, context: InvocationContext, request: CompleteRequestRequest) -> Result<CompleteRequestResponse, PrivacyRequestWorkerCompleteRequestInvocationError> {
        self.complete_request.invoke_with_context(COMPLETE_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestWorkerCompleteRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerCompleteRequestInvocationError::Domain)
    }

    pub async fn fail_request(&self, request: FailRequestRequest) -> Result<FailRequestResponse, PrivacyRequestWorkerFailRequestInvocationError> {
        self.fail_request.invoke(FAIL_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestWorkerFailRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerFailRequestInvocationError::Domain)
    }

    pub async fn fail_request_with_context(&self, context: InvocationContext, request: FailRequestRequest) -> Result<FailRequestResponse, PrivacyRequestWorkerFailRequestInvocationError> {
        self.fail_request.invoke_with_context(FAIL_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestWorkerFailRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerFailRequestInvocationError::Domain)
    }

    pub async fn process_request(&self, request: ProcessRequestRequest) -> Result<ProcessRequestResponse, PrivacyRequestWorkerProcessRequestInvocationError> {
        self.process_request.invoke(PROCESS_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestWorkerProcessRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerProcessRequestInvocationError::Domain)
    }

    pub async fn process_request_with_context(&self, context: InvocationContext, request: ProcessRequestRequest) -> Result<ProcessRequestResponse, PrivacyRequestWorkerProcessRequestInvocationError> {
        self.process_request.invoke_with_context(PROCESS_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestWorkerProcessRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerProcessRequestInvocationError::Domain)
    }

    pub async fn retry_request(&self, request: RetryRequestRequest) -> Result<RetryRequestResponse, PrivacyRequestWorkerRetryRequestInvocationError> {
        self.retry_request.invoke(RETRY_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestWorkerRetryRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerRetryRequestInvocationError::Domain)
    }

    pub async fn retry_request_with_context(&self, context: InvocationContext, request: RetryRequestRequest) -> Result<RetryRequestResponse, PrivacyRequestWorkerRetryRequestInvocationError> {
        self.retry_request.invoke_with_context(RETRY_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestWorkerRetryRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWorkerRetryRequestInvocationError::Domain)
    }
}

impl CapabilityClient for PrivacyRequestWorkerClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            claim_next: dependencies.one::<PrivacyRequestWorkerClaimNext>()?,
            claim_request: dependencies.one::<PrivacyRequestWorkerClaimRequest>()?,
            complete_request: dependencies.one::<PrivacyRequestWorkerCompleteRequest>()?,
            fail_request: dependencies.one::<PrivacyRequestWorkerFailRequest>()?,
            process_request: dependencies.one::<PrivacyRequestWorkerProcessRequest>()?,
            retry_request: dependencies.one::<PrivacyRequestWorkerRetryRequest>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for PrivacyRequestWorkerClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    claim_next: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWorkerClaimNext>()?,
                    claim_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWorkerClaimRequest>()?,
                    complete_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWorkerCompleteRequest>()?,
                    fail_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWorkerFailRequest>()?,
                    process_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWorkerProcessRequest>()?,
                    retry_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWorkerRetryRequest>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWorkerClaimNextInvocationError {
    Domain(ClaimNextError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWorkerClaimRequestInvocationError {
    Domain(ClaimRequestError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWorkerCompleteRequestInvocationError {
    Domain(CompleteRequestError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWorkerFailRequestInvocationError {
    Domain(FailRequestError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWorkerProcessRequestInvocationError {
    Domain(ProcessRequestError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWorkerRetryRequestInvocationError {
    Domain(RetryRequestError),
    Runtime(RuntimeFailure),
}
