// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.privacy-request@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const PRIVACY_REQUEST_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PRIVACY_REQUEST_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_privacy_request { () => { "{\"capability_id\":\"lenso.privacy-request@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"create_request\",\"get_request\",\"list_requests\",\"withdraw_request\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_privacy_request_client { () => { "{\"capability_id\":\"lenso.privacy-request@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_privacy_request_client { () => { "{\"capability_id\":\"lenso.privacy-request@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CREATE_REQUEST_OPERATION: &str = "create_request";
pub const GET_REQUEST_OPERATION: &str = "get_request";
pub const LIST_REQUESTS_OPERATION: &str = "list_requests";
pub const WITHDRAW_REQUEST_OPERATION: &str = "withdraw_request";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRequestRequest {
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: CreateRequestRequestKind,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateRequestRequestKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: CreateRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: CreateRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: CreateRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CreateRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequestRequest {
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "request_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_ref: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: GetRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: GetRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "result_items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub result_items: Vec<GetRequestResponseResultItemsItem>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: GetRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetRequestResponseResultItemsItem {
    #[serde(rename = "item_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub item_name: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: String,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: String,
    #[serde(rename = "provider_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub provider_instance: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum GetRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequestsRequest {
    #[serde(rename = "cursor")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "state")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<ListRequestsRequestState>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListRequestsRequestState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequestsResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "requests")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requests: Vec<ListRequestsResponseRequestsItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequestsResponseRequestsItem {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: ListRequestsResponseRequestsItemIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ListRequestsResponseRequestsItemKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: ListRequestsResponseRequestsItemState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListRequestsResponseRequestsItemIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListRequestsResponseRequestsItemKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ListRequestsResponseRequestsItemState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListRequestsError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WithdrawRequestRequest {
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WithdrawRequestResponse {
    #[serde(rename = "assignee_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assignee_subject: Option<String>,
    #[serde(rename = "completed_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed_at: Option<String>,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "deadline_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deadline_at: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "failure_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_reason: Option<String>,
    #[serde(rename = "identifier")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identifier: String,
    #[serde(rename = "identity_status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub identity_status: WithdrawRequestResponseIdentityStatus,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: WithdrawRequestResponseKind,
    #[serde(rename = "legal_hold")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub legal_hold: bool,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "overdue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub overdue: bool,
    #[serde(rename = "paused_reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub paused_reason: Option<String>,
    #[serde(rename = "request_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub request_id: String,
    #[serde(rename = "requester_subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester_subject: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: WithdrawRequestResponseState,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum WithdrawRequestResponseIdentityStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum WithdrawRequestResponseKind {
    #[serde(rename = "access")]
    Access,
    #[serde(rename = "export")]
    Export,
    #[serde(rename = "erasure")]
    Erasure,
    #[serde(rename = "correction")]
    Correction,
    #[serde(rename = "restriction")]
    Restriction,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum WithdrawRequestResponseState {
    #[serde(rename = "pending_verification")]
    PendingVerification,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "claimed")]
    Claimed,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "awaiting_completion")]
    AwaitingCompletion,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum WithdrawRequestError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    InvalidTransition,
    RequestNotFound,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct PrivacyRequestCreateRequest;
impl RequestCapability for PrivacyRequestCreateRequest {
    type Request = CreateRequestRequest;
    type Response = CreateRequestResponse;
    type DomainError = CreateRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_request(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestGetRequest;
impl RequestCapability for PrivacyRequestGetRequest {
    type Request = GetRequestRequest;
    type Response = GetRequestResponse;
    type DomainError = GetRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_request(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestListRequests;
impl RequestCapability for PrivacyRequestListRequests {
    type Request = ListRequestsRequest;
    type Response = ListRequestsResponse;
    type DomainError = ListRequestsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_REQUESTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_requests(context, request)
    }
}

#[derive(Debug)]
pub struct PrivacyRequestWithdrawRequest;
impl RequestCapability for PrivacyRequestWithdrawRequest {
    type Request = WithdrawRequestRequest;
    type Response = WithdrawRequestResponse;
    type DomainError = WithdrawRequestError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != WITHDRAW_REQUEST_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<PrivacyRequestRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).withdraw_request(context, request)
    }
}

impl serde::Serialize for CreateRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListRequestsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListRequestsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for WithdrawRequestError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::InvalidTransition => serializer.serialize_str("invalid_transition"),
            Self::RequestNotFound => serializer.serialize_str("request_not_found"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for WithdrawRequestError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "invalid_transition" => Ok(Self::InvalidTransition),
                "request_not_found" => Ok(Self::RequestNotFound),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_create_request_request(value: &CreateRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_request_request(wire: &str) -> Result<CreateRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_request_response(value: &CreateRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_request_response(wire: &str) -> Result<CreateRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_request_error(value: &CreateRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_request_error(wire: &str) -> Result<CreateRequestError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_request_request(value: &GetRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request_request(wire: &str) -> Result<GetRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_request_response(value: &GetRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request_response(wire: &str) -> Result<GetRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_request_error(value: &GetRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_request_error(wire: &str) -> Result<GetRequestError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_requests_request(value: &ListRequestsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requests_request(wire: &str) -> Result<ListRequestsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_requests_response(value: &ListRequestsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requests_response(wire: &str) -> Result<ListRequestsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_requests_error(value: &ListRequestsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requests_error(wire: &str) -> Result<ListRequestsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_withdraw_request_request(value: &WithdrawRequestRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_withdraw_request_request(wire: &str) -> Result<WithdrawRequestRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_withdraw_request_response(value: &WithdrawRequestResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_withdraw_request_response(wire: &str) -> Result<WithdrawRequestResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_withdraw_request_error(value: &WithdrawRequestError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_withdraw_request_error(wire: &str) -> Result<WithdrawRequestError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestCreateRequestResult {
    fn __lenso_into_result(self) -> Result<Result<CreateRequestResponse, CreateRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestCreateRequestResult for Result<CreateRequestResponse, CreateRequestError> {
    fn __lenso_into_result(self) -> Result<Result<CreateRequestResponse, CreateRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestCreateRequestResult for Result<Result<CreateRequestResponse, CreateRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateRequestResponse, CreateRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestCreateRequestResult for Result<CreateRequestResponse, lenso_plugin_authoring::PluginError<CreateRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateRequestResponse, CreateRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestCreateRequestResult for Result<CreateRequestResponse, PrivacyRequestCreateRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateRequestResponse, CreateRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestCreateRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestCreateRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestGetRequestResult {
    fn __lenso_into_result(self) -> Result<Result<GetRequestResponse, GetRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestGetRequestResult for Result<GetRequestResponse, GetRequestError> {
    fn __lenso_into_result(self) -> Result<Result<GetRequestResponse, GetRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestGetRequestResult for Result<Result<GetRequestResponse, GetRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetRequestResponse, GetRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestGetRequestResult for Result<GetRequestResponse, lenso_plugin_authoring::PluginError<GetRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetRequestResponse, GetRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestGetRequestResult for Result<GetRequestResponse, PrivacyRequestGetRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetRequestResponse, GetRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestGetRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestGetRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestListRequestsResult {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestListRequestsResult for Result<ListRequestsResponse, ListRequestsError> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestListRequestsResult for Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestListRequestsResult for Result<ListRequestsResponse, lenso_plugin_authoring::PluginError<ListRequestsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestListRequestsResult for Result<ListRequestsResponse, PrivacyRequestListRequestsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestListRequestsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestListRequestsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoPrivacyRequestWithdrawRequestResult {
    fn __lenso_into_result(self) -> Result<Result<WithdrawRequestResponse, WithdrawRequestError>, RuntimeFailure>;
}
impl __LensoIntoPrivacyRequestWithdrawRequestResult for Result<WithdrawRequestResponse, WithdrawRequestError> {
    fn __lenso_into_result(self) -> Result<Result<WithdrawRequestResponse, WithdrawRequestError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoPrivacyRequestWithdrawRequestResult for Result<Result<WithdrawRequestResponse, WithdrawRequestError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<WithdrawRequestResponse, WithdrawRequestError>, RuntimeFailure> { self }
}
impl __LensoIntoPrivacyRequestWithdrawRequestResult for Result<WithdrawRequestResponse, lenso_plugin_authoring::PluginError<WithdrawRequestError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<WithdrawRequestResponse, WithdrawRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoPrivacyRequestWithdrawRequestResult for Result<WithdrawRequestResponse, PrivacyRequestWithdrawRequestInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<WithdrawRequestResponse, WithdrawRequestError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(PrivacyRequestWithdrawRequestInvocationError::Domain(error)) => Ok(Err(error)),
            Err(PrivacyRequestWithdrawRequestInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait PrivacyRequestProvider: fmt::Debug + 'static {
    fn create_request(&self, context: InvocationContext, request: CreateRequestRequest) -> NativeRequestFuture<PrivacyRequestCreateRequest>;
    fn get_request(&self, context: InvocationContext, request: GetRequestRequest) -> NativeRequestFuture<PrivacyRequestGetRequest>;
    fn list_requests(&self, context: InvocationContext, request: ListRequestsRequest) -> NativeRequestFuture<PrivacyRequestListRequests>;
    fn withdraw_request(&self, context: InvocationContext, request: WithdrawRequestRequest) -> NativeRequestFuture<PrivacyRequestWithdrawRequest>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_privacy_request {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportPrivacyRequest;
        impl $crate::PrivacyRequestProvider for $plugin {
        fn create_request(&self, context: __LensoNativeSupportPrivacyRequest::InvocationContext, request: $crate::CreateRequestRequest) -> __LensoNativeSupportPrivacyRequest::NativeRequestFuture<$crate::PrivacyRequestCreateRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestCreateRequestResult::__lenso_into_result(result)
            })
        }
        fn get_request(&self, context: __LensoNativeSupportPrivacyRequest::InvocationContext, request: $crate::GetRequestRequest) -> __LensoNativeSupportPrivacyRequest::NativeRequestFuture<$crate::PrivacyRequestGetRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestGetRequestResult::__lenso_into_result(result)
            })
        }
        fn list_requests(&self, context: __LensoNativeSupportPrivacyRequest::InvocationContext, request: $crate::ListRequestsRequest) -> __LensoNativeSupportPrivacyRequest::NativeRequestFuture<$crate::PrivacyRequestListRequests> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_requests(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestListRequestsResult::__lenso_into_result(result)
            })
        }
        fn withdraw_request(&self, context: __LensoNativeSupportPrivacyRequest::InvocationContext, request: $crate::WithdrawRequestRequest) -> __LensoNativeSupportPrivacyRequest::NativeRequestFuture<$crate::PrivacyRequestWithdrawRequest> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::withdraw_request(&plugin, context, request).await;
                $crate::__LensoIntoPrivacyRequestWithdrawRequestResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct PrivacyRequestRequestEndpoint { provider: Rc<dyn PrivacyRequestProvider> }

#[derive(Debug)]
pub struct PrivacyRequestEndpoint<P: PrivacyRequestProvider> { provider: Rc<P>, request_endpoint: PrivacyRequestRequestEndpoint }
impl<P: PrivacyRequestProvider> PrivacyRequestEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn PrivacyRequestProvider> = provider.clone();
        Self { provider, request_endpoint: PrivacyRequestRequestEndpoint { provider: request_provider } }
    }
}

impl<P: PrivacyRequestProvider> NativeRequestEndpoint for PrivacyRequestEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CREATE_REQUEST_OPERATION,
        GET_REQUEST_OPERATION,
        LIST_REQUESTS_OPERATION,
        WITHDRAW_REQUEST_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CREATE_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<CreateRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<GetRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_REQUESTS_OPERATION => {
                let Ok(request) = request.downcast::<ListRequestsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_requests(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            WITHDRAW_REQUEST_OPERATION => {
                let Ok(request) = request.downcast::<WithdrawRequestRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).withdraw_request(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_privacy_request {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::PrivacyRequestEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_privacy_request {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_privacy_request!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct PrivacyRequestClient {
    create_request: NativeRequestHandle<PrivacyRequestCreateRequest>,
    get_request: NativeRequestHandle<PrivacyRequestGetRequest>,
    list_requests: NativeRequestHandle<PrivacyRequestListRequests>,
    withdraw_request: NativeRequestHandle<PrivacyRequestWithdrawRequest>,
}
impl PrivacyRequestClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn create_request(&self, request: CreateRequestRequest) -> Result<CreateRequestResponse, PrivacyRequestCreateRequestInvocationError> {
        self.create_request.invoke(CREATE_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestCreateRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestCreateRequestInvocationError::Domain)
    }

    pub async fn create_request_with_context(&self, context: InvocationContext, request: CreateRequestRequest) -> Result<CreateRequestResponse, PrivacyRequestCreateRequestInvocationError> {
        self.create_request.invoke_with_context(CREATE_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestCreateRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestCreateRequestInvocationError::Domain)
    }

    pub async fn get_request(&self, request: GetRequestRequest) -> Result<GetRequestResponse, PrivacyRequestGetRequestInvocationError> {
        self.get_request.invoke(GET_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestGetRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestGetRequestInvocationError::Domain)
    }

    pub async fn get_request_with_context(&self, context: InvocationContext, request: GetRequestRequest) -> Result<GetRequestResponse, PrivacyRequestGetRequestInvocationError> {
        self.get_request.invoke_with_context(GET_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestGetRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestGetRequestInvocationError::Domain)
    }

    pub async fn list_requests(&self, request: ListRequestsRequest) -> Result<ListRequestsResponse, PrivacyRequestListRequestsInvocationError> {
        self.list_requests.invoke(LIST_REQUESTS_OPERATION, request).await
            .map_err(PrivacyRequestListRequestsInvocationError::Runtime)?
            .map_err(PrivacyRequestListRequestsInvocationError::Domain)
    }

    pub async fn list_requests_with_context(&self, context: InvocationContext, request: ListRequestsRequest) -> Result<ListRequestsResponse, PrivacyRequestListRequestsInvocationError> {
        self.list_requests.invoke_with_context(LIST_REQUESTS_OPERATION, context, request).await
            .map_err(PrivacyRequestListRequestsInvocationError::Runtime)?
            .map_err(PrivacyRequestListRequestsInvocationError::Domain)
    }

    pub async fn withdraw_request(&self, request: WithdrawRequestRequest) -> Result<WithdrawRequestResponse, PrivacyRequestWithdrawRequestInvocationError> {
        self.withdraw_request.invoke(WITHDRAW_REQUEST_OPERATION, request).await
            .map_err(PrivacyRequestWithdrawRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWithdrawRequestInvocationError::Domain)
    }

    pub async fn withdraw_request_with_context(&self, context: InvocationContext, request: WithdrawRequestRequest) -> Result<WithdrawRequestResponse, PrivacyRequestWithdrawRequestInvocationError> {
        self.withdraw_request.invoke_with_context(WITHDRAW_REQUEST_OPERATION, context, request).await
            .map_err(PrivacyRequestWithdrawRequestInvocationError::Runtime)?
            .map_err(PrivacyRequestWithdrawRequestInvocationError::Domain)
    }
}

impl CapabilityClient for PrivacyRequestClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            create_request: dependencies.one::<PrivacyRequestCreateRequest>()?,
            get_request: dependencies.one::<PrivacyRequestGetRequest>()?,
            list_requests: dependencies.one::<PrivacyRequestListRequests>()?,
            withdraw_request: dependencies.one::<PrivacyRequestWithdrawRequest>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for PrivacyRequestClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    create_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestCreateRequest>()?,
                    get_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestGetRequest>()?,
                    list_requests: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestListRequests>()?,
                    withdraw_request: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<PrivacyRequestWithdrawRequest>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestCreateRequestInvocationError {
    Domain(CreateRequestError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestGetRequestInvocationError {
    Domain(GetRequestError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestListRequestsInvocationError {
    Domain(ListRequestsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum PrivacyRequestWithdrawRequestInvocationError {
    Domain(WithdrawRequestError),
    Runtime(RuntimeFailure),
}
